import type { Product, Order } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Classic Linen Shirt",
    description:
      "A timeless linen shirt crafted from premium European linen. Perfect for warm days and layered looks.",
    price: 79.0,
    images: [
      "/white-linen-button-shirt-woman-professional.jpg",
      "/white-linen-shirt-back.png",
      "/beige-linen-shirt-woman.jpg",
      "/black-linen-shirt-woman.jpg",
    ],
    category: "women",
    subcategory: "Tops",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "White", hex: "#F5F5DC" },
      { name: "Camel", hex: "#D2B48C" },
      { name: "Navy", hex: "#1E3A5F" },
      { name: "Sage", hex: "#9CAF88" },
    ],
    rating: 4.8,
    reviews: 120,
    reviewsList: [
      {
        id: "r1",
        productId: "1",
        userId: "u1",
        userName: "Sarah J.",
        rating: 5,
        title: "Absolutely Perfect",
        text: "The quality of the linen is outstanding. It's so soft and breathable. It has become my go-to shirt for the summer. Fits true to size.",
        createdAt: "2024-10-15",
      },
      {
        id: "r2",
        productId: "1",
        userId: "u2",
        userName: "Emily R.",
        rating: 5,
        title: "Great Wardrobe Staple",
        text: "I love how versatile this blouse is. I can dress it up for work or wear it casually with jeans. It wrinkles a bit, but that's expected with linen.",
        createdAt: "2024-10-10",
      },
      {
        id: "r3",
        productId: "1",
        userId: "u3",
        userName: "Jessica L.",
        rating: 5,
        title: "Beautiful Color",
        text: "I bought the sage green color and it's even more beautiful in person. The fabric feels luxurious and I get compliments every time I wear it.",
        createdAt: "2024-10-05",
      },
    ],
    inStock: true,
    featured: true,
  },
  {
    id: "2",
    name: "High-Waist Denim Jeans",
    description:
      "Classic high-waisted jeans with a comfortable stretch fit. Versatile and timeless.",
    price: 110.0,
    images: ["/high-waist-light-blue-denim-jeans.jpg"],
    category: "women",
    subcategory: "Tops",
    sizes: ["24", "26", "28", "30", "32"],
    colors: [
      { name: " white", hex: "#ffffff" },
      { name: "Blue", hex: "#495bffff" },
    ],
    rating: 4.6,
    reviews: 89,
    inStock: true,
    featured: true,
  },
  {
    id: "3",
    name: "The Everyday Tote Bag",
    description:
      "A spacious leather tote bag perfect for work or weekend errands.",
    price: 150.0,
    images: ["/tan-leather-tote-bag-minimalist.jpg"],
    category: "women",
    subcategory: "Accessories",
    sizes: ["One Size"],
    colors: [{ name: "Brown", hex: "#D2691E" }],
    rating: 4.9,
    reviews: 156,
    inStock: true,
    featured: true,
  },
  {
    id: "4",
    name: "Minimalist Leather Sneaker",
    description: "Clean, minimalist sneakers crafted from premium leather.",
    price: 125.0,
    images: ["/white-minimalist-leather-sneakers.jpg"],
    category: "men",
    subcategory: "Shoes",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#000000" },
    ],
    rating: 4.7,
    reviews: 203,
    inStock: true,
    featured: true,
  },
  {
    id: "5",
    name: "Essential Crewneck Tee",
    description:
      "A perfectly fitted crewneck t-shirt made from organic cotton.",
    price: 45.0,
    images: ["/olive-green-crewneck-tshirt-man.jpg"],
    category: "men",
    subcategory: "Tops",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Olive", hex: "#808000" }],
    rating: 4.5,
    reviews: 312,
    inStock: true,
    bestSeller: true,
  },
  {
    id: "6",
    name: "Modern Straight-Leg Chino",
    description: "Versatile chinos with a modern straight-leg fit.",
    price: 95.0,
    images: ["/khaki-straight-leg-chino-pants-man.jpg"],
    category: "men",
    subcategory: "Pants",
    sizes: ["28", "30", "32", "34", "36"],
    colors: [
      { name: "Khaki", hex: "#C3B091" },
      { name: "White", hex: "white" },
    ],
    rating: 4.6,
    reviews: 178,
    inStock: true,
    bestSeller: true,
  },
  {
    id: "7",
    name: "Floral Midi Sundress",
    description:
      "A beautiful floral print midi dress perfect for summer occasions.",
    price: 130.0,
    images: ["/floral-print-midi-sundress-woman.jpg"],
    category: "women",
    subcategory: "Dresses",
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "Floral Print", hex: "#FFB6C1" }],
    rating: 4.8,
    reviews: 95,
    inStock: true,
    bestSeller: true,
  },
  {
    id: "8",
    name: "Cashmere Crew Sweater",
    description: "Luxuriously soft cashmere sweater for ultimate comfort.",
    price: 180.0,
    images: ["/beige-cashmere-crew-neck-sweater.jpg"],
    category: "women",
    subcategory: "Sweaters",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "Beige", hex: "#FFFDD0" }],
    rating: 4.9,
    reviews: 234,
    inStock: true,
    bestSeller: true,
  },
  {
    id: "9",
    name: "Floral Sundress",
    description: "Light and airy floral sundress for warm summer days.",
    price: 89.99,
    images: ["/floral-sundress-woman-beige-background.jpg"],
    category: "women",
    subcategory: "Dresses",
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "Floral", hex: "#F5DEB3" }],
    rating: 4.2,
    reviews: 12,
    inStock: true,
  },
  {
    id: "10",
    name: "Classic Linen Shirt Dress",
    description: "Elegant linen shirt dress with a relaxed fit.",
    price: 120.0,
    images: ["/white-linen-shirt-dress-woman.jpg"],
    category: "women",
    subcategory: "Dresses",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "White", hex: "#FFFFFF" }],
    rating: 4.5,
    reviews: 34,
    inStock: true,
  },
  {
    id: "11",
    name: "Denim Midi Dress",
    description: "Trendy denim midi dress with button front detail.",
    price: 95.5,
    images: ["/denim-midi-dress-woman-blue.jpg"],
    category: "women",
    subcategory: "Jeans",
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "Blue", hex: "#4169E1" }],
    rating: 4.3,
    reviews: 21,
    inStock: true,
  },
  {
    id: "12",
    name: "Satin Slip Dress",
    description: "Elegant satin slip dress for evening occasions.",
    price: 79.99,
    images: ["/black-satin-slip-dress-woman.jpg"],
    category: "women",
    subcategory: "Dresses",
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Champagne", hex: "#F7E7CE" },
    ],
    rating: 4.8,
    reviews: 8,
    inStock: true,
  },
  {
    id: "13",
    name: "Ribbed Knit Dress",
    description: "Comfortable ribbed knit dress with a flattering fit.",
    price: 110.0,
    images: ["/brown-ribbed-knit-dress-woman.jpg"],
    category: "women",
    subcategory: "Dresses",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "Brown", hex: "#8B4513" }],
    rating: 4.4,
    reviews: 15,
    inStock: true,
  },
  {
    id: "14",
    name: "Ruffled Wrap Dress",
    description: "Stunning ruffled wrap dress in bold red.",
    price: 135.0,
    images: ["/Ruffled Wrap Dress.jpeg", "/Ruffled Wrap Dress2.jpeg"],
    category: "women",
    subcategory: "Dresses",
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "blue", hex: "#0000FF" },
      { name: "red", hex: "#FF0000" },
    ],
    rating: 4.7,
    reviews: 42,
    inStock: true,
  },
  {
    id: "15",
    name: "Classic Trench Coat",
    description: "Timeless trench coat with a modern silhouette.",
    price: 185.0,
    images: ["/Classic Trench Coat2.jpg", "/Classic Trench Coat.jpg"],
    category: "women",
    subcategory: "Outerwear",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Beige", hex: "#C19A6B" },
      { name: "Brown", hex: "#0e5d04ff" },
    ],
    rating: 4.8,
    reviews: 67,
    inStock: true,
  },
  {
    id: "16",
    name: "Silk Blend Blouse",
    description: "Elegant silk blend blouse with a relaxed fit.",
    price: 75.0,
    images: ["/Silk Blend Blouse.jpg", "/Silk Blend Blouse2.jpg"],
    category: "women",
    subcategory: "Topss",
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "Pink", hex: "#FFB6C1" }],
    rating: 4.6,
    reviews: 45,
    inStock: true,
  },

  {
    id: "17",
    name: "Tailored Trousers",
    description: "Classic tailored trousers with a modern fit.",
    price: 120.0,
    images: ["/Tailored Trousers.jpg", "/Tailored Trousers2.jpg"],
    category: "women",
    subcategory: "Pants",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "Black", hex: "#000000" }],
    rating: 4.7,
    reviews: 89,
    inStock: true,
  },
  {
    id: "18",
    name: "The Essential Linen Blouse",
    description:
      "Crafted from the finest European linen, this blouse is a testament to timeless style and comfort. Its relaxed fit and breathable fabric make it an essential piece for any wardrobe, perfect for warm days or layered looks.",
    price: 85.0,
    images: [
      "/The Essential Linen Blouse.jpg",
      "/The Essential Linen Blouse2.jpg",
    ],
    category: "women",
    subcategory: "Topss",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "Black", hex: "#000000" }],
    rating: 4.8,
    reviews: 120,
    reviewsList: [
      {
        id: "r1",
        productId: "18",
        userId: "u1",
        userName: "Sarah J.",
        rating: 5,
        title: "Absolutely Perfect",
        text: "The quality of the linen is outstanding. It's so soft and breathable. It has become my go-to shirt for the summer. Fits true to size.",
        createdAt: "2024-10-15",
      },
      {
        id: "r2",
        productId: "18",
        userId: "u2",
        userName: "Emily R.",
        rating: 5,
        title: "Great Wardrobe Staple",
        text: "I love how versatile this blouse is. I can dress it up for work or wear it casually with jeans. It wrinkles a bit, but that's expected with linen.",
        createdAt: "2024-10-10",
      },
      {
        id: "r3",
        productId: "18",
        userId: "u3",
        userName: "Jessica L.",
        rating: 5,
        title: "Beautiful Color",
        text: "I bought the sage green color and it's even more beautiful in person. The fabric feels luxurious and I get compliments every time I wear it.",
        createdAt: "2024-10-05",
      },
    ],
    inStock: true,
    featured: true,
  },
  {
    id: "19",
    name: "Classic Denim Jeans",
    description: "High-quality denim jeans with a comfortable fit.",
    price: 120.0,
    images: ["/Classic Denim Jeans.jpg", "/Classic Denim Jeans2.jpg"],
    category: "women",
    subcategory: "Jeans",
    sizes: ["28", "30", "32", "34"],
    colors: [{ name: "Blue", hex: "#4169E1" }],
    rating: 4.5,
    reviews: 78,
    inStock: true,
  },
  {
    id: "20",
    name: "Linen Blend Shirt",
    description: "Comfortable linen blend shirt for casual occasions.",
    price: 75.0,
    images: ["/Linen Blend Shirt.jpg", "/Linen Blend Shirt2.jpg"],
    category: "men",
    subcategory: "Tops",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Black", hex: "#000000" }],
    rating: 4.4,
    reviews: 56,
    inStock: true,
  },
  {
    id: "21",
    name: "Cotton Shirt",
    description: "Comfortable linen shirt for casual occasions.",
    price: 75.0,
    images: ["/Cotton_shirt.jpg", "/Cotton_shirt2.jpg"],
    category: "men",
    subcategory: "Tops",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Blue", hex: "#0000FF" }],
    rating: 4.4,
    reviews: 56,
    inStock: true,
  },
  {
    id: "22",
    name: "Shirt Cotton",
    description: "Comfortable shirt for casual occasions.",
    price: 75.0,
    images: ["/Shirt_cotton.jpg"],
    category: "men",
    subcategory: "Tops",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Brown", hex: "#8B4513" }],
    rating: 4.4,
    reviews: 56,
    inStock: true,
  },
  {
    id: "23",
    name: "Maxi Beige Skirt",
    description: "Timeless trench Skirt with a modern silhouette.",
    price: 199.0,
    images: ["/Skirt.jpeg", "/Skirt2.jpeg"],
    category: "women",
    subcategory: "Skirts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "Beige", hex: "#C19A6B" }],
    rating: 4.8,
    reviews: 67,
    inStock: true,
  },
  {
    id: "24",
    name: "Shearlock Wood Set",
    description:
      "Wrap yourself in understated luxury with our finest wool set.",
    price: 160.0,
    images: ["/Shearlock Wood Set.jpg"],
    category: "kids",
    subcategory: "Skirts",
    sizes: ["S", "M", "L"],
    colors: [{ name: "Beige", hex: "#C19A6B" }],
    rating: 4.8,
    reviews: 67,
    inStock: true,
  },
  {
    id: "25",
    name: "Toddler Boy Training Suit",
    description:
      "Elevate your casual style with our High-Quality Acid Wash T-Shirt.",
    price: 220.0,
    images: ["/Toddler Boy Training Suit.jpg"],
    category: "kids",
    subcategory: "Skirts",
    sizes: ["S", "M", "L"],
    colors: [{ name: "Blue", hex: "#4169E1" }],
    rating: 4.8,
    reviews: 67,
    inStock: true,
  },
  {
    id: "26",
    name: "The Vibing Panther T-shirt ",
    description:
      "Elevate your casual style with our High-Quality Acid Wash T-Shirt.",
    price: 220.0,
    images: ["/The Vibing Panther T-shirt.jpg"],
    category: "kids",
    subcategory: "Skirts",
    sizes: ["S", "M", "L"],
    colors: [{ name: "Black", hex: "#000000" }],
    rating: 4.8,
    reviews: 67,
    inStock: true,
  },
  {
    id: "27",
    name: "Your Way Hoodie Blue",
    description: "Stay cozy and trendy with our oversized hoodie.",
    price: 170.0,
    images: ["/Your Way Hoodie Blue.jpg"],
    category: "kids",
    subcategory: "Skirts",
    sizes: ["S", "M", "L"],
    colors: [{ name: "Blue", hex: "#4169E1" }],
    rating: 4.8,
    reviews: 67,
    inStock: true,
  },
  {
    id: "28",
    name: "Airplane Mode Brown Hoodie",
    description: "Stay cozy and trendy with our oversized hoodie.",
    price: 120.0,
    images: ["/Airplane Mode Brown Hoodie.jpg"],
    category: "kids",
    subcategory: "Skirts",
    sizes: ["S", "M", "L"],
    colors: [{ name: "Black", hex: "#000000" }],
    rating: 4.8,
    reviews: 67,
    inStock: true,
  },
];

export const sampleOrders: Order[] = [
  {
    id: "EF123456789",
    userId: "1",
    items: [],
    status: "processing",
    total: 210.6,
    subtotal: 195.0,
    shipping: 0,
    taxes: 15.6,
    paymentMethod: "credit-card",
    shippingAddress: {
      fullName: "John Doe",
      street: "123 Fashion Ave",
      city: "New York",
      postalCode: "10001",
      country: "USA",
    },
    phone: "(123) 456-7890",
    createdAt: "2024-10-24",
    estimatedDelivery: "October 26, 2024",
    statusHistory: [
      { status: "placed", date: "October 24" },
      { status: "processing", date: "October 24" },
    ],
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all") return products;
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getBestSellers(): Product[] {
  return products.filter((p) => p.bestSeller);
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowercaseQuery) ||
      p.description.toLowerCase().includes(lowercaseQuery) ||
      p.category.toLowerCase().includes(lowercaseQuery)
  );
}

export function filterProducts(
  category?: string,
  subcategory?: string,
  sizes?: string[],
  colors?: string[],
  minPrice?: number,
  maxPrice?: number
): Product[] {
  return products.filter((p) => {
    if (category && category !== "all" && p.category !== category) return false;
    if (subcategory && p.subcategory !== subcategory) return false;
    if (sizes && sizes.length > 0 && !sizes.some((s) => p.sizes.includes(s)))
      return false;
    if (
      colors &&
      colors.length > 0 &&
      !colors.some((c) => p.colors.some((pc) => pc.name === c))
    )
      return false;
    if (minPrice !== undefined && p.price < minPrice) return false;
    if (maxPrice !== undefined && p.price > maxPrice) return false;
    return true;
  });
}
